version: "3"

services:

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./source:/app
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    container_name: app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    volumes:
      - ./source:/app
      - ./config/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  rabbitmq:
    image: rabbitmq:3.7.28-management
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./storage/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-root}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-catalog}

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-web_shop}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_USER: ${MYSQL_USER:-admin}
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - "3306:3306"