framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async_product_import:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Message\Serializer\ProductImportJsonSerializer
                options:
                    exchange:
                        name: product_import_exchange
                    queues:
                        product_import_queue: ~

            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\ProductImportMessage: async_product_import
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
